#!/usr/bin/env tsx
/**
 * Generate a fresh VAPID keypair and write both keys to SSM Parameter Store
 * as SecureString values, replacing whatever is at the parameter paths.
 *
 * CloudFormation cannot create SecureString parameters, so the SAM template
 * provisions placeholder String parameters; this script deletes those and
 * recreates them as SecureString with real key material.
 *
 * Usage:
 *   pnpm tsx scripts/gen-vapid.ts --stage dev
 *   pnpm tsx scripts/gen-vapid.ts --stage prod --profile garageborrow-prod
 */

import { parseArgs } from "node:util";
import {
  SSMClient,
  PutParameterCommand,
  DeleteParameterCommand,
  ParameterNotFound,
} from "@aws-sdk/client-ssm";
import webpush from "web-push";

const REGION = "us-east-2";

async function main(): Promise<void> {
  const { values } = parseArgs({
    options: {
      stage: { type: "string" },
      profile: { type: "string" },
    },
  });

  const stage = values.stage;
  if (!stage) {
    console.error("error: --stage <dev|prod> is required");
    process.exit(1);
  }
  if (values.profile) {
    process.env.AWS_PROFILE = values.profile;
  }

  const keys = webpush.generateVAPIDKeys();
  console.log(`Generated VAPID keypair (publicKey length=${keys.publicKey.length}).`);

  const ssm = new SSMClient({ region: REGION });
  const publicName = `/garageborrow/${stage}/vapid_public_key`;
  const privateName = `/garageborrow/${stage}/vapid_private_key`;

  await replaceAsSecureString(ssm, publicName, keys.publicKey);
  await replaceAsSecureString(ssm, privateName, keys.privateKey);

  console.log("Done.");
  console.log(`  ${publicName}  (SecureString)`);
  console.log(`  ${privateName} (SecureString)`);
}

async function replaceAsSecureString(ssm: SSMClient, name: string, value: string): Promise<void> {
  // Cannot change a parameter's Type via Overwrite — must delete & recreate.
  try {
    await ssm.send(new DeleteParameterCommand({ Name: name }));
  } catch (err) {
    if (!(err instanceof ParameterNotFound)) {
      throw err;
    }
  }
  await ssm.send(
    new PutParameterCommand({
      Name: name,
      Value: value,
      Type: "SecureString",
      Overwrite: false,
      Description: "VAPID key for web-push (generated by scripts/gen-vapid.ts).",
    }),
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
